### ISSUE TITLE
Not able to select weighting method

### ISSUE THREAD

**Issue by adewolff** [DCPROGS/CVFIT#1]
Hi there! I'm trying to use your code for an undergraduate research project. After loading my csv into the cvfit_example notebook I'm not able to select the weighting, as it just keeps asking me to enter the mode number. Is there something I'm doing wrong? 
![issue](https://i.imgur.com/suD6DB6.png)

**Comment by remislp** [comment]
Please, check updated notebook.  Weighting method selection removed from the example.  Thanks for reporting the problem.

**Comment by adewolff** [comment]
Thanks!
